#main.yml
#This workflow will install Python dependencies, lint using Black, run tests using Pytest 
#and Deploy the FastAPI app to Heroku
name: fastapi-github-actions-test

# set variables that are used below
env:
  #Replace $PROJECT_ID with your project ID
  PROJECT_ID: drew-2022-10
  IMAGE_NAME: gcr.io/$PROJECT_ID/app
  JWT_SECRET_KEY: my-32-character-ultra-secure-and-ultra-long-secret
  SERVICE_ACCOUNT: github-actions-service-account
  WORKLOAD_IDENTITY_PROVIDER_LOCATION: "projects/1016062054874/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider"
 
on: 
  #Trigger the workflow on a push event to YourBranchName branch only
  push: 
    branches: [YourBranchName]

#A workflow job running sequentially
jobs:
   # Need to add these 3 lines to add "id-token" with the intended permissions.

  build:
    #runs-on: defines The workflow runner
    runs-on: ubuntu-latest 

    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    #steps: defines a series of tasks executed by the Job
    steps:
    - uses: actions/checkout@v2
    - run: |   # To fetch all history for all tags and branches
        git fetch --prune --unshallow  

    #Task for setting up Python 3.8 using actions/setup-python@v2 Github action
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 # Modify python version HERE

    #Task for installing dependencies, multi-line command
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Task for linting with black
    - name: Lint with black
      run: |
        # Code formatting with black, check every python file in the src directory 
        black src 
        black --check src
    
    # Task for testing with pytest
    - name: Test with pytest
      run: |
        pytest
      
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        # Replace with your Workload Identity Provider Location
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER_LOCATION }}
        # Replace with your GitHub Service Account
        service_account: ${{ env.SERVICE_ACCOUNT }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Build Docker image
      run: docker build . -t ${{ env.IMAGE_NAME }}

    - name: Push Docker image
      run: docker push ${{ env.IMAGE_NAME }} --remove-signatures

    - id: deploy
      name: Deploy Docker image
      uses: "google-github-actions/deploy-cloudrun@v0"
      with:
        image: ${{ env.IMAGE_NAME }}
        region: us-east5
        service: app
        flags: --port=8080 --allow-unauthenticated

    # Example of using the output
    - name: Test URL
      run: curl "${{ steps.deploy.outputs.url }}"